In [55]:
import numpy as np


# List vs Numpy

In [14]:
a=list(range(1,10000000))

In [8]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
arr=np.arange(1,10000000)

In [10]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#for checking size 
import sys

In [16]:
sys.getsizeof(a)

80000056

In [17]:
sys.getsizeof(arr)

40000108

In [18]:
%%time #to get time taken for that paricular range
a=list(range(1,10000000))
sys.getsizeof(a)

CPU times: total: 78.1 ms
Wall time: 144 ms


80000056

In [19]:
%%time #to get time taken for that paricular range
arr=np.arange(1,10000000)
sys.getsizeof(arr)

CPU times: total: 0 ns
Wall time: 11 ms


40000108

here the time taken by the list is more than the compared to the array 

# creation of arrays

### From basic data structure

In [20]:
#from tuple
values=(1,2,3,4,5,6,7,8)
arr=np.array(values)


In [21]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
#from list
values=[1,2,3,4,5,6,7,8]
arr=np.array(values)


In [23]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

# from zeros

In [25]:
np.zeros((4,3)) #creating the null array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# from ones

In [29]:
a=np.ones((3,3))

In [30]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
a.dtype

dtype('float64')

In [32]:
type(a)

numpy.ndarray

### from a value

In [37]:
c=np.full((4,4),5) #it is creating the matrix by taking the value and the
                  #size of that particual function or otherwise known as the dimension

In [38]:
c

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [42]:
np.full((2),3)

array([3, 3])

# from arange

In [43]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [44]:
np.arange(50,100)

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# from linspace

In [49]:
np.linspace(10,20,7) #from one number to the another it consits difference between two numbers is same

array([10.        , 11.66666667, 13.33333333, 15.        , 16.66666667,
       18.33333333, 20.        ])

In [50]:
np.linspace(10,100,20)

array([ 10.        ,  14.73684211,  19.47368421,  24.21052632,
        28.94736842,  33.68421053,  38.42105263,  43.15789474,
        47.89473684,  52.63157895,  57.36842105,  62.10526316,
        66.84210526,  71.57894737,  76.31578947,  81.05263158,
        85.78947368,  90.52631579,  95.26315789, 100.        ])

# from random

In [52]:
np.random.randint(10,100,5) #from random it is creating the random numbers or the values by taking 
#how many numbers we want ehere heare 5 is the the number of the data or the numbers we want

array([21, 52, 26, 89, 91])

In [53]:
salaries=np.random.randint(20000,100000,30)

In [54]:
salaries

array([41145, 87938, 79022, 34194, 51762, 29828, 99796, 26179, 51512,
       97178, 79103, 21592, 32603, 84757, 56825, 94196, 81525, 78353,
       29217, 90549, 79496, 35437, 23958, 69792, 31275, 87460, 62922,
       92852, 32676, 39392])

# Diffrent dimension arrays

In [64]:
a=np.array([[1,2,3,4],[5,6,7,8]])

In [65]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
a.ndim

2

### at the time of creating

In [68]:
b=np.array([1,2,3,4,5,6],ndmin=2)

In [69]:
b

array([[1, 2, 3, 4, 5, 6]])

In [70]:
b.ndim

2

# After creating

In [72]:
b=np.array([10,20,30,40,50,60,70,80])

In [75]:
b.reshape(2,2,2)

array([[[10, 20],
        [30, 40]],

       [[50, 60],
        [70, 80]]])

In [77]:
np.reshape(np.array([10,20,30,40,50,60,70,80]),(1,2,4))

array([[[10, 20, 30, 40],
        [50, 60, 70, 80]]])

# Attributes of arrays

In [81]:
d=np.array([10,20,30,40,50,60,70,80])

In [84]:
e=d.reshape(1,2,4)

In [85]:
e.ndim #no of dimensions present in the array

3

In [86]:
e.size #no of elements present in it

8

In [87]:
e.dtype

dtype('int32')

In [88]:
e.itemsize #returns the memory occupied by the single element

4

In [89]:
e.nbytes #total memory occupied by the array

32

# 1. measure of central tendency

In [6]:
salaries=np.random.randint(20000,100000,30)

In [7]:
salaries

array([36347, 93966, 41497, 30323, 97502, 20905, 45949, 92616, 73675,
       71753, 78029, 30966, 59357, 70897, 42715, 65809, 75816, 90577,
       22080, 37274, 81163, 92896, 62651, 79321, 89592, 28788, 80128,
       31340, 89734, 68948])

In [8]:
#mean
np.mean(salaries)

62753.8

In [9]:
np.median(salaries)

69922.5

# 2. Measure of dispersion

In [10]:
x=min(salaries)

In [11]:
y=max(salaries)

In [12]:
y-x #range

76597

In [13]:
np.var(salaries)

598001643.0266666

In [14]:
np.percentile(salaries,25)

38329.75

In [15]:
np.percentile(salaries,50)

69922.5

In [16]:
np.percentile(salaries,75)

80904.25

In [17]:
np.percentile(salaries,100)

97502.0

In [18]:
np.max(salaries)

97502

In [19]:
np.min(salaries)

20905

In [20]:
np.std(salaries)

24454.072115430317

# Indexing and Slicing

In [23]:
arr=np.array([10,15,14,132,])

In [24]:
salaries=np.random.randint(20000,100000,30)

In [25]:
salaries

array([30692, 82691, 53916, 87284, 71053, 54377, 57644, 48920, 63521,
       52727, 87420, 39954, 59987, 77114, 91167, 35766, 55649, 40118,
       70306, 85962, 34077, 84505, 68871, 26519, 72440, 79768, 43547,
       22359, 50069, 86497])

In [44]:
sal=salaries.reshape(5,6)

In [45]:
sal

array([[30692, 82691, 53916, 87284, 71053, 54377],
       [57644, 48920, 63521, 52727, 87420, 39954],
       [59987, 77114, 91167, 35766, 55649, 40118],
       [70306, 85962, 34077, 84505, 68871, 26519],
       [72440, 79768, 43547, 22359, 50069, 86497]])

In [46]:
sal[0]

array([30692, 82691, 53916, 87284, 71053, 54377])

In [47]:
sal[:,5]

array([54377, 39954, 40118, 26519, 86497])

In [48]:
sal[:,4]

array([71053, 87420, 55649, 68871, 50069])

In [54]:
sal[0:4,0:4]

array([[30692, 82691, 53916, 87284],
       [57644, 48920, 63521, 52727],
       [59987, 77114, 91167, 35766],
       [70306, 85962, 34077, 84505]])

In [57]:
sal[0:2,1:3]

array([[82691, 53916],
       [48920, 63521]])

In [58]:
sal[1:4,3:5]

array([[52727, 87420],
       [35766, 55649],
       [84505, 68871]])

# Mathmatical Operations

In [59]:
sal+sal

array([[ 61384, 165382, 107832, 174568, 142106, 108754],
       [115288,  97840, 127042, 105454, 174840,  79908],
       [119974, 154228, 182334,  71532, 111298,  80236],
       [140612, 171924,  68154, 169010, 137742,  53038],
       [144880, 159536,  87094,  44718, 100138, 172994]])

In [65]:
sal+10000

array([[ 40692,  92691,  63916,  97284,  81053,  64377],
       [ 67644,  58920,  73521,  62727,  97420,  49954],
       [ 69987,  87114, 101167,  45766,  65649,  50118],
       [ 80306,  95962,  44077,  94505,  78871,  36519],
       [ 82440,  89768,  53547,  32359,  60069,  96497]])

In [66]:
sal-10000

array([[20692, 72691, 43916, 77284, 61053, 44377],
       [47644, 38920, 53521, 42727, 77420, 29954],
       [49987, 67114, 81167, 25766, 45649, 30118],
       [60306, 75962, 24077, 74505, 58871, 16519],
       [62440, 69768, 33547, 12359, 40069, 76497]])

In [67]:
sal*2

array([[ 61384, 165382, 107832, 174568, 142106, 108754],
       [115288,  97840, 127042, 105454, 174840,  79908],
       [119974, 154228, 182334,  71532, 111298,  80236],
       [140612, 171924,  68154, 169010, 137742,  53038],
       [144880, 159536,  87094,  44718, 100138, 172994]])

In [68]:
sal>50000

array([[False,  True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True, False],
       [ True,  True,  True, False,  True, False],
       [ True,  True, False,  True,  True, False],
       [ True,  True, False, False,  True,  True]])

In [69]:
sal[sal>50000]

array([82691, 53916, 87284, 71053, 54377, 57644, 63521, 52727, 87420,
       59987, 77114, 91167, 55649, 70306, 85962, 84505, 68871, 72440,
       79768, 50069, 86497])

In [71]:
sal[sal<50000]

array([30692, 48920, 39954, 35766, 40118, 34077, 26519, 43547, 22359])

In [76]:
sal[(sal>40000) & (sal <50000)]

array([48920, 40118, 43547])

# Numpy Data Types and Type casting

In [78]:
sal.dtype

dtype('int32')

In [79]:
np.iinfo("int8")

iinfo(min=-128, max=127, dtype=int8)

In [80]:
np.iinfo("int16")

iinfo(min=-32768, max=32767, dtype=int16)

In [81]:
np.iinfo("int32")

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [85]:
np.iinfo("uint")

iinfo(min=0, max=4294967295, dtype=uint32)

In [86]:
np.iinfo("uint8")

iinfo(min=0, max=255, dtype=uint8)

In [92]:
np.finfo("float16")

finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

In [100]:
import random

In [101]:
ages=np.random.randint(2,100,20)

In [102]:
ages

array([ 6, 66, 68, 95, 29, 42, 73, 56, 55, 91, 48, 25, 83, 27, 39, 52, 58,
       20, 73, 83])

In [104]:
ages.dtype

dtype('int32')

In [105]:
ages.nbytes

80

In [108]:
age=ages.astype("int16")

In [109]:
age.dtype

dtype('int16')

In [110]:
a=age.astype("int8")

In [111]:
a.dtype

dtype('int8')

In [112]:
a

array([ 6, 66, 68, 95, 29, 42, 73, 56, 55, 91, 48, 25, 83, 27, 39, 52, 58,
       20, 73, 83], dtype=int8)

In [113]:
np.array([131,2,3,4,5,98,120,70],dtype="int8")

C:\Users\Ganji Bhaskar\AppData\Local\Temp\ipykernel_20008\3706819795.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 131 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([131,2,3,4,5,98,120,70],dtype="int8")


array([-125,    2,    3,    4,    5,   98,  120,   70], dtype=int8)

In [115]:
ages[2]=45

In [116]:
ages

array([ 6, 66, 45, 95, 29, 42, 73, 56, 55, 91, 48, 25, 83, 27, 39, 52, 58,
       20, 73, 83])

In [117]:
rating=np.array([1,2,3,4600,4,5,])

In [119]:
q1=np.quantile(rating,0.25)
q3=np.quantile(rating,0.75)
IQR=q3-q1
lower=q1-(1.5*IQR)
upper=q3+(1.5*IQR)

In [120]:
q1

2.25

In [121]:
q3

4.75

In [122]:
IQR

2.5

In [123]:
lower

-1.5

In [124]:
upper

8.5

In [125]:
rating[(rating<lower) | (rating>upper)]

array([4600])

# Replacing the values(np.where())

In [126]:
rating

array([   1,    2,    3, 4600,    4,    5])

In [131]:
cond=(rating<lower) | (rating>upper)

#### np.where(condition,True_value,False_value)

In [132]:
np.where(cond,3,rating) # where condition is using to replace the value with some particular number 
#which is in the rang here rating is keeping the remaing values as same

array([1, 2, 3, 3, 4, 5])

In [137]:
a=np.random.randint(10000,50000,30)

In [138]:
a

array([19318, 17936, 30553, 29399, 34896, 13926, 39779, 43220, 44950,
       32006, 40822, 34735, 14826, 14038, 14188, 10936, 14620, 15257,
       35671, 45656, 23641, 34369, 21754, 40879, 10226, 47556, 18182,
       47572, 18981, 47438])

In [139]:
cond=a<50000

In [140]:
np.where(cond,a+5000,a)

array([24318, 22936, 35553, 34399, 39896, 18926, 44779, 48220, 49950,
       37006, 45822, 39735, 19826, 19038, 19188, 15936, 19620, 20257,
       40671, 50656, 28641, 39369, 26754, 45879, 15226, 52556, 23182,
       52572, 23981, 52438])

# constants

In [141]:
np.pi

3.141592653589793

In [142]:
np.e

2.718281828459045

In [143]:
np.nan

nan

In [144]:
np.inf

inf

In [145]:
np.arange(1,10)/0

C:\Users\Ganji Bhaskar\AppData\Local\Temp\ipykernel_20008\2456871482.py:1: RuntimeWarning: divide by zero encountered in divide
  np.arange(1,10)/0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [10]:
b=np.random.randint(1,10,9)

In [11]:
b

array([5, 4, 8, 4, 8, 1, 1, 1, 8])

In [12]:
b.shape

(9,)

In [13]:
q1=np.quantile(b,0.25)

In [14]:
q1

1.0

In [15]:
q3=np.quantile(b,0.75)

In [16]:
q3

8.0

In [17]:
IQR=q3-q1

In [18]:
IQR

7.0

In [19]:
lower=q1-(1.5*IQR)

In [20]:
lower

-9.5

In [24]:
upper=q3+(1.5*IQR)

In [25]:
upper

18.5

In [28]:
b[(b<lower) | (b >upper)]

array([], dtype=int32)

In [37]:
c=np.array([1,2,3,4,200])

In [38]:
c

array([  1,   2,   3,   4, 200])

In [39]:
c.shape

(5,)

In [41]:
q1=np.quantile(c,0.25)

In [42]:
q3=np.quantile(c,0.75)

In [43]:
IQr=q3-q1

In [44]:
lower=q1-(1.5*IQr)

In [45]:
upper=q3+(1.5*IQr)

In [46]:
q1

2.0

In [47]:
q3

4.0

In [48]:
IQr

2.0

In [49]:
lower

-1.0

In [50]:
upper

7.0

In [51]:
c[(c<lower) | (c >upper)]

array([200])

In [52]:
(c<lower) | (c >upper)

array([False, False, False, False,  True])

In [53]:
c

array([  1,   2,   3,   4, 200])

In [2]:
d=np.random.randint(10000,50000,40)

In [3]:
e=d.reshape(8,5)

In [4]:
e

array([[30706, 34708, 13483, 38168, 24771],
       [24575, 27727, 27202, 14593, 36745],
       [36441, 38219, 34864, 45028, 43143],
       [28727, 18086, 24409, 21870, 14793],
       [27273, 15117, 47689, 30052, 32190],
       [39619, 31924, 45323, 14909, 13267],
       [45767, 36792, 30801, 20580, 30534],
       [46435, 49812, 36648, 12697, 30111]])

In [69]:
e[:,0:1]

array([[43617],
       [39868],
       [20811],
       [44089],
       [33066],
       [27308],
       [19414],
       [13263]])

In [70]:
d=np.random.randint(10000,50000,9)

In [73]:
f=d.reshape(3,3)

In [74]:
f

array([[19160, 41627, 20159],
       [49767, 34976, 36972],
       [13971, 28283, 36343]])

In [75]:
f[:]

array([[19160, 41627, 20159],
       [49767, 34976, 36972],
       [13971, 28283, 36343]])

In [76]:
f[1:]

array([[49767, 34976, 36972],
       [13971, 28283, 36343]])

In [78]:
f[0,1]

41627

In [79]:
f[0:2]

array([[19160, 41627, 20159],
       [49767, 34976, 36972]])

In [80]:
f

array([[19160, 41627, 20159],
       [49767, 34976, 36972],
       [13971, 28283, 36343]])

In [81]:
f[0,0]

19160

In [87]:
f[0:3]

array([[19160, 41627, 20159],
       [49767, 34976, 36972],
       [13971, 28283, 36343]])

In [91]:
f[:1,]

array([[19160, 41627, 20159]])

In [92]:
f[:,0]

array([19160, 49767, 13971])

In [95]:
f[:2,1]

array([41627, 34976])

In [96]:
f[0:2,1:]

array([[41627, 20159],
       [34976, 36972]])

In [97]:
f

array([[19160, 41627, 20159],
       [49767, 34976, 36972],
       [13971, 28283, 36343]])

In [100]:
f[1:]

array([[49767, 34976, 36972],
       [13971, 28283, 36343]])

In [102]:
f[1:,0:2]

array([[49767, 34976],
       [13971, 28283]])

In [105]:
f[1:]

array([[49767, 34976, 36972],
       [13971, 28283, 36343]])

In [106]:
f[1:,1:]

array([[34976, 36972],
       [28283, 36343]])

In [108]:
f[1:,1:2]

array([[34976],
       [28283]])

In [5]:
e

array([[30706, 34708, 13483, 38168, 24771],
       [24575, 27727, 27202, 14593, 36745],
       [36441, 38219, 34864, 45028, 43143],
       [28727, 18086, 24409, 21870, 14793],
       [27273, 15117, 47689, 30052, 32190],
       [39619, 31924, 45323, 14909, 13267],
       [45767, 36792, 30801, 20580, 30534],
       [46435, 49812, 36648, 12697, 30111]])

In [6]:
e[2:4,2:4]

array([[34864, 45028],
       [24409, 21870]])

In [7]:
e

array([[30706, 34708, 13483, 38168, 24771],
       [24575, 27727, 27202, 14593, 36745],
       [36441, 38219, 34864, 45028, 43143],
       [28727, 18086, 24409, 21870, 14793],
       [27273, 15117, 47689, 30052, 32190],
       [39619, 31924, 45323, 14909, 13267],
       [45767, 36792, 30801, 20580, 30534],
       [46435, 49812, 36648, 12697, 30111]])

In [8]:
e[4:7,:2]

array([[27273, 15117],
       [39619, 31924],
       [45767, 36792]])

In [1]:
import numpy as np

# Stacking and Splitting(joining)

In [2]:
arr1=np.random.randint(1,20,12).reshape(3,4)

In [3]:
arr2=np.random.randint(10,30,12).reshape(3,4)

In [4]:
arr1

array([[11,  1,  3,  7],
       [18,  1, 18,  9],
       [18,  3, 18, 17]])

In [5]:
arr2

array([[27, 19, 12, 13],
       [16, 28, 16, 19],
       [27, 19, 28, 22]])

In [6]:
np.hstack((arr1,arr2))

array([[11,  1,  3,  7, 27, 19, 12, 13],
       [18,  1, 18,  9, 16, 28, 16, 19],
       [18,  3, 18, 17, 27, 19, 28, 22]])

In [7]:
np.vstack((arr1,arr2))

array([[11,  1,  3,  7],
       [18,  1, 18,  9],
       [18,  3, 18, 17],
       [27, 19, 12, 13],
       [16, 28, 16, 19],
       [27, 19, 28, 22]])

In [8]:
np.dstack((arr1,arr2))

array([[[11, 27],
        [ 1, 19],
        [ 3, 12],
        [ 7, 13]],

       [[18, 16],
        [ 1, 28],
        [18, 16],
        [ 9, 19]],

       [[18, 27],
        [ 3, 19],
        [18, 28],
        [17, 22]]])

In [9]:
np.concatenate((arr1,arr2))#if we donot provide the axis the default axis is 0 then it is vstack

array([[11,  1,  3,  7],
       [18,  1, 18,  9],
       [18,  3, 18, 17],
       [27, 19, 12, 13],
       [16, 28, 16, 19],
       [27, 19, 28, 22]])

In [10]:
np.concatenate((arr1,arr2),axis=1) #if axis=1 then it will become hstack

array([[11,  1,  3,  7, 27, 19, 12, 13],
       [18,  1, 18,  9, 16, 28, 16, 19],
       [18,  3, 18, 17, 27, 19, 28, 22]])

# Spliting

In [11]:
arr1

array([[11,  1,  3,  7],
       [18,  1, 18,  9],
       [18,  3, 18, 17]])

In [13]:
np.split(arr1,3)

[array([[11,  1,  3,  7]]),
 array([[18,  1, 18,  9]]),
 array([[18,  3, 18, 17]])]

In [14]:
np.split(arr1,4,axis=1)

[array([[11],
        [18],
        [18]]),
 array([[1],
        [1],
        [3]]),
 array([[ 3],
        [18],
        [18]]),
 array([[ 7],
        [ 9],
        [17]])]

In [17]:
np.array_split(arr1,4,axis=0)#splits as per sections

[array([[11,  1,  3,  7]]),
 array([[18,  1, 18,  9]]),
 array([[18,  3, 18, 17]]),
 array([], shape=(0, 4), dtype=int32)]

# view vs copy

In [18]:
arr1

array([[11,  1,  3,  7],
       [18,  1, 18,  9],
       [18,  3, 18, 17]])

In [19]:
arr2

array([[27, 19, 12, 13],
       [16, 28, 16, 19],
       [27, 19, 28, 22]])

# view

In [23]:
arr1_view=arr1.view() #muttable it is reflected on the original array

In [24]:
arr1_view 

array([[11,  1,  3,  7],
       [18,  1, 18,  9],
       [18,  3, 18, 17]])

In [26]:
arr1_view[0,3]=2000

In [27]:
arr1_view


array([[  11,    1,    3, 2000],
       [  18,    1,   18,    9],
       [  18,    3,   18,   17]])

In [28]:
arr1

array([[  11,    1,    3, 2000],
       [  18,    1,   18,    9],
       [  18,    3,   18,   17]])

# copy

In [29]:
arr2_copy=arr2.copy()

In [30]:
arr2_copy

array([[27, 19, 12, 13],
       [16, 28, 16, 19],
       [27, 19, 28, 22]])

In [32]:
arr2_copy[0,2]=2000

In [33]:
arr2_copy # copy is immutable it is not reflected on the original array

array([[  27,   19, 2000,   13],
       [  16,   28,   16,   19],
       [  27,   19,   28,   22]])

In [34]:
arr2

array([[27, 19, 12, 13],
       [16, 28, 16, 19],
       [27, 19, 28, 22]])

# ravel vs flatten

In [35]:
arr2

array([[27, 19, 12, 13],
       [16, 28, 16, 19],
       [27, 19, 28, 22]])

In [43]:
f=np.ravel(arr2) # is same as view but it store in the 1-dimensional array
f

array([27, 19, 12, 13, 16, 28, 16, 19, 27, 19, 28, 22])

In [44]:
f[2]=60000


In [45]:
f

array([   27,    19, 60000,    13,    16,    28,    16,    19,    27,
          19,    28,    22])

In [46]:
arr2

array([[   27,    19, 60000,    13],
       [   16,    28,    16,    19],
       [   27,    19,    28,    22]])

# flatten

In [47]:
arr1

array([[  11,    1,    3, 2000],
       [  18,    1,   18,    9],
       [  18,    3,   18,   17]])

In [48]:
f=arr1.flatten() # is same as copybut it store in the 1-dimensional array

In [49]:
f

array([  11,    1,    3, 2000,   18,    1,   18,    9,   18,    3,   18,
         17])

In [52]:
f[3]=8000

In [53]:
f

array([  11,    1,    3, 8000,   18,    1,   18,    9,   18,    3,   18,
         17])

In [54]:
arr1

array([[  11,    1,    3, 2000],
       [  18,    1,   18,    9],
       [  18,    3,   18,   17]])

# Set Operations

In [55]:
arr1=np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
arr2=np.arange(8,17).reshape(3,3)
arr2

array([[ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

In [58]:
np.union1d(arr1,arr2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [59]:
np.intersect1d(arr1,arr2)

array([8, 9])

In [62]:
np.unique(arr1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a=np.array([1,2,3,4,1,2,3,4,1,23,4])

In [65]:
np.unique(a)

array([ 1,  2,  3,  4, 23])

In [66]:
np.setdiff1d(arr1,arr2)

array([1, 2, 3, 4, 5, 6, 7])

In [67]:
np.setdiff1d(arr2,arr1)

array([10, 11, 12, 13, 14, 15, 16])

# Matrix Operations

In [68]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
np.matrix([[1,2,3],[4,5,6],[7,8,9]])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [71]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
np.eye(3,4) #it creates identity as per our requriment we can give any no of rows or columns

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [75]:
a.T #rows becomes colums and columns becomes as rows

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [77]:
a.diagonal()

array([1, 5, 9])

# Linear Algebra

In [78]:
a=np.matrix([[1,2],[2,-3]])

In [79]:
b=np.matrix([[3],[7]])

In [80]:
np.linalg.solve(a,b)

matrix([[ 3.28571429],
        [-0.14285714]])

In [86]:
c=np.matrix([[1,10,-3],[10,-1,30],[0,1,1]])


In [87]:
d=np.matrix([[9],[3],[100]])

In [88]:
np.linalg.solve(c,d)

matrix([[-182.49689441],
        [  37.80745342],
        [  62.19254658]])

In [90]:
f=np.matrix([[10,2,6],[5,3,6],[2,4,3]])

In [91]:
f

matrix([[10,  2,  6],
        [ 5,  3,  6],
        [ 2,  4,  3]])

In [92]:
np.linalg.det(f)

-72.0

In [94]:
np.linalg.inv(f)

matrix([[ 0.20833333, -0.25      ,  0.08333333],
        [ 0.04166667, -0.25      ,  0.41666667],
        [-0.19444444,  0.5       , -0.27777778]])

In [95]:
np.linalg.eigvals(f)

array([13.98770596,  3.48802315, -1.47572911])

In [96]:
s,v,d=np.linalg.svd(f) #singular values for the decomposition

In [97]:
s

matrix([[-0.78017224,  0.54555499,  0.30610625],
        [-0.54939806, -0.36354285, -0.75232863],
        [-0.2991539 , -0.75512009,  0.58335289]])

In [98]:
v

array([14.91391985,  3.87603656,  1.24552608])

In [99]:
d


matrix([[-0.74742392, -0.29537199, -0.59507383],
        [ 0.54891006, -0.77914614, -0.30270288],
        [ 0.37423953,  0.55288939, -0.74448512]])

# sorting and searching

In [100]:
arr3=np.random.randint(1,100,15)

In [101]:
arr3

array([19, 64, 70, 95, 28, 90, 46, 26, 52, 88, 66, 84, 82, 32, 50])

In [102]:
np.sort(arr3)

array([19, 26, 28, 32, 46, 50, 52, 64, 66, 70, 82, 84, 88, 90, 95])

In [106]:
np.argsort(arr3) #returns the index position of a array before sorting

array([ 0,  7,  4, 13,  6, 14,  8,  1, 10,  2, 12, 11,  9,  5,  3],
      dtype=int64)

In [107]:
np.argmax(arr3) ##return the max index position of the array before sorting

3

In [108]:
np.argmin(arr3) #return the minimum index position of the array before sorting

0

In [111]:
arr1=np.random.randint(1,10,9).reshape(3,3)

In [112]:
arr2=np.random.randint(15,30,9).reshape(3,3)

In [113]:
arr1

array([[2, 2, 6],
       [2, 7, 5],
       [3, 9, 5]])

In [114]:
arr2

array([[24, 21, 23],
       [29, 16, 21],
       [24, 23, 24]])

In [115]:
np.dot(arr1,arr2)

array([[250, 212, 232],
       [371, 269, 313],
       [453, 322, 378]])

In [1]:
import numpy as np

In [15]:
Ages  =np.random.randint(1,100,30)
Ages

array([23, 29, 72, 85, 47, 18, 56, 51, 58, 14, 23, 11, 26, 75, 88, 83, 61,
       14, 50, 44, 35, 49, 56, 10, 44, 84, 43, 25, 88, 59])

In [16]:
np.mean(Ages[Ages>55])

72.08333333333333

In [17]:
minimum=np.min(Ages)
minimum

10

In [18]:
Ages[Ages>18]

array([23, 29, 72, 85, 47, 56, 51, 58, 23, 26, 75, 88, 83, 61, 50, 44, 35,
       49, 56, 44, 84, 43, 25, 88, 59])

In [19]:
np.std(Ages)===

24.352252918820923

In [20]:
maximum=np.max(Ages)
maximum

88

In [21]:
range1=maximum - minimum
range1

78

In [22]:
Q1=np.quantile(Ages,0.25)
Q3=np.quantile(Ages,0.75)
IQR=Q3-Q1
Lower=Q1-(1.5*IQR)
Upper=Q3+(1.5*IQR)
Ages[(Ages<Q1) & (Ages>Q3)]

array([], dtype=int32)

# Mathmatical Operations

In [1]:
import numpy as np

In [2]:
a=6.2

In [3]:
np.ceil(a)

7.0

In [4]:
np.floor(a)

6.0

In [5]:
np.round(a)

6.0

In [6]:
arr1=np.array([1.2,2.3,3.5,4.4,5.9,6.7])

In [7]:
np.floor(arr1)

array([1., 2., 3., 4., 5., 6.])

In [8]:
np.ceil(arr1)

array([2., 3., 4., 5., 6., 7.])

# Array Broadcasting

In [10]:
arr1=np.array([[1,2,3],[3,4,5]])
arr1

array([[1, 2, 3],
       [3, 4, 5]])

In [11]:
arr2=np.array([[1,2,3]])

In [12]:
arr2

array([[1, 2, 3]])

In [13]:
arr1+arr2

array([[2, 4, 6],
       [4, 6, 8]])

In [14]:
arr3=np.array([[1]])

In [16]:
arr1+arr3 #in this array array3 consiting of the single element so it is broadcasting as [[1,1,1],[1,1,1]]

array([[2, 3, 4],
       [4, 5, 6]])

In [17]:
arr4=np.array([[1,2]])

In [18]:
arr1+arr4

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [20]:
arr5=np.array([[1],[2],[3]])

In [21]:
arr1+arr5

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

In [23]:
    arr1+arr5.T

array([[2, 4, 6],
       [4, 6, 8]])

In [26]:
arr6=np.array([[1,2],[3,4],[5,6]])
arr6

array([[1, 2],
       [3, 4],
       [5, 6]])

# File Handling with numpy

In [28]:
marks=np.array([45,65,33,23,np.nan,77,99,45,87])

In [29]:
marks

array([45., 65., 33., 23., nan, 77., 99., 45., 87.])

In [30]:
np.mean(marks)

nan

In [42]:
a=np.nanmean(marks)
a

59.25

In [33]:
np.nanmedian(marks)

55.0

In [34]:
np.nanmax(marks)

99.0

In [35]:
np.nanmin(marks)

23.0

np.where(cond,True_value,False_value)

In [45]:
np.where(np.isnan(marks),np.nanmean(marks),marks)

array([45.  , 65.  , 33.  , 23.  , 59.25, 77.  , 99.  , 45.  , 87.  ])

In [47]:
np.isnan(marks)

array([False, False, False, False,  True, False, False, False, False])

In [51]:
marks=np.array([45,65,33,23,np.nan,77,99,45,87])

In [53]:
np.isnan(marks).sum()

1

# csv files

In [130]:
df=np.genfromtxt('salary.csv',dtype="int32",delimiter=",")
df

array([[    -1,     -1,     -1],
       [    43,  20000,      5],
       [    33,  40000,      5],
       [    32, 500000,      3],
       [    55,  20000,      6],
       [    44,  15000,      8],
       [     2,  45000,      1],
       [    23,  20000,      5],
       [    45,     -1,      0],
       [   566, 361266,      2],
       [    34,  31267,      2],
       [    -1, 482848,     11],
       [    77,  43747,      5],
       [    23,     -1,      6],
       [   111,  89423,      4],
       [    23,   8589,     -1],
       [    55,  44243,      2],
       [    66,  43444,      2],
       [    33,     -1,      9],
       [    77,   4283,      3],
       [    33,  99238,      1],
       [    12,  37373,     -1]])

In [117]:
df=df[1:,]
df

array([[    43,  20000,      5],
       [    33,  40000,      5],
       [    32, 500000,      3],
       [    55,  20000,      6],
       [    44,  15000,      8],
       [     2,  45000,      1],
       [    23,  20000,      5],
       [    45,     -1,      0],
       [   566, 361266,      2],
       [    34,  31267,      2],
       [    -1, 482848,     11],
       [    77,  43747,      5],
       [    23,     -1,      6],
       [   111,  89423,      4],
       [    23,   8589,     -1],
       [    55,  44243,      2],
       [    66,  43444,      2],
       [    33,     -1,      9],
       [    77,   4283,      3],
       [    33,  99238,      1],
       [    12,  37373,     -1]])

In [118]:
age=df[:,0]
age

array([ 43,  33,  32,  55,  44,   2,  23,  45, 566,  34,  -1,  77,  23,
       111,  23,  55,  66,  33,  77,  33,  12])

In [119]:
age=np.where(age==-1,np.nan,age)
age

array([ 43.,  33.,  32.,  55.,  44.,   2.,  23.,  45., 566.,  34.,  nan,
        77.,  23., 111.,  23.,  55.,  66.,  33.,  77.,  33.,  12.])

In [120]:
age=np.where(np.isnan(age),np.nanmean(age),age)
age

array([ 43.  ,  33.  ,  32.  ,  55.  ,  44.  ,   2.  ,  23.  ,  45.  ,
       566.  ,  34.  ,  69.35,  77.  ,  23.  , 111.  ,  23.  ,  55.  ,
        66.  ,  33.  ,  77.  ,  33.  ,  12.  ])

In [123]:
df=df[1:]
df

array([[    43,  20000,      5],
       [    33,  40000,      5],
       [    32, 500000,      3],
       [    55,  20000,      6],
       [    44,  15000,      8],
       [     2,  45000,      1],
       [    23,  20000,      5],
       [    45,     -1,      0],
       [   566, 361266,      2],
       [    34,  31267,      2],
       [    -1, 482848,     11],
       [    77,  43747,      5],
       [    23,     -1,      6],
       [   111,  89423,      4],
       [    23,   8589,     -1],
       [    55,  44243,      2],
       [    66,  43444,      2],
       [    33,     -1,      9],
       [    77,   4283,      3],
       [    33,  99238,      1],
       [    12,  37373,     -1]])

In [124]:
salary=df[:,1]
salary

array([ 20000,  40000, 500000,  20000,  15000,  45000,  20000,     -1,
       361266,  31267, 482848,  43747,     -1,  89423,   8589,  44243,
        43444,     -1,   4283,  99238,  37373])

In [125]:
salary==-1

array([False, False, False, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False, False])

In [126]:
salary=np.where(salary==-1,np.nan,salary)

In [127]:
salary

array([ 20000.,  40000., 500000.,  20000.,  15000.,  45000.,  20000.,
           nan, 361266.,  31267., 482848.,  43747.,     nan,  89423.,
         8589.,  44243.,  43444.,     nan,   4283.,  99238.,  37373.])

In [128]:
salary=np.where(np.isnan(salary),np.nanmean(salary),salary)

In [129]:
salary

array([ 20000.        ,  40000.        , 500000.        ,  20000.        ,
        15000.        ,  45000.        ,  20000.        , 105873.38888889,
       361266.        ,  31267.        , 482848.        ,  43747.        ,
       105873.38888889,  89423.        ,   8589.        ,  44243.        ,
        43444.        , 105873.38888889,   4283.        ,  99238.        ,
        37373.        ])

In [131]:
df=df[1:,]
df

array([[    43,  20000,      5],
       [    33,  40000,      5],
       [    32, 500000,      3],
       [    55,  20000,      6],
       [    44,  15000,      8],
       [     2,  45000,      1],
       [    23,  20000,      5],
       [    45,     -1,      0],
       [   566, 361266,      2],
       [    34,  31267,      2],
       [    -1, 482848,     11],
       [    77,  43747,      5],
       [    23,     -1,      6],
       [   111,  89423,      4],
       [    23,   8589,     -1],
       [    55,  44243,      2],
       [    66,  43444,      2],
       [    33,     -1,      9],
       [    77,   4283,      3],
       [    33,  99238,      1],
       [    12,  37373,     -1]])

In [132]:
dist=df[:,2]
dist

array([ 5,  5,  3,  6,  8,  1,  5,  0,  2,  2, 11,  5,  6,  4, -1,  2,  2,
        9,  3,  1, -1])

In [133]:
dist=np.where(dist==-1,np.nan,dist)
dist

array([ 5.,  5.,  3.,  6.,  8.,  1.,  5.,  0.,  2.,  2., 11.,  5.,  6.,
        4., nan,  2.,  2.,  9.,  3.,  1., nan])

In [135]:
dist=np.where(np.isnan(dist),np.ceil(np.nanmean(dist)),dist)

In [136]:
dist

array([ 5.,  5.,  3.,  6.,  8.,  1.,  5.,  0.,  2.,  2., 11.,  5.,  6.,
        4.,  5.,  2.,  2.,  9.,  3.,  1.,  5.])

In [140]:
age

array([ 43.  ,  33.  ,  32.  ,  55.  ,  44.  ,   2.  ,  23.  ,  45.  ,
       566.  ,  34.  ,  69.35,  77.  ,  23.  , 111.  ,  23.  ,  55.  ,
        66.  ,  33.  ,  77.  ,  33.  ,  12.  ])

In [141]:
salary

array([ 20000.        ,  40000.        , 500000.        ,  20000.        ,
        15000.        ,  45000.        ,  20000.        , 105873.38888889,
       361266.        ,  31267.        , 482848.        ,  43747.        ,
       105873.38888889,  89423.        ,   8589.        ,  44243.        ,
        43444.        , 105873.38888889,   4283.        ,  99238.        ,
        37373.        ])

In [142]:
dist

array([ 5.,  5.,  3.,  6.,  8.,  1.,  5.,  0.,  2.,  2., 11.,  5.,  6.,
        4.,  5.,  2.,  2.,  9.,  3.,  1.,  5.])

In [143]:
age[age>60]

array([566.  ,  69.35,  77.  , 111.  ,  66.  ,  77.  ])

In [144]:
np.where(age>100,60,age)

array([43.  , 33.  , 32.  , 55.  , 44.  ,  2.  , 23.  , 45.  , 60.  ,
       34.  , 69.35, 77.  , 23.  , 60.  , 23.  , 55.  , 66.  , 33.  ,
       77.  , 33.  , 12.  ])